package com.infoedge.jrandomizer.providers;

/**
 * Created by gagandeep on 31/7/16.
 */

public class CityProvider extends Provider<String[]> {
    private CityProvider(Class<String[]> clazz) {
        super(clazz);
    }

    @Override
    public String[] provide() {
        if (mLoadedData == null) {
            mLoadedData = new String[]{
                    "Angasmarca",
                    "President Roxas",
                    "Monsanto",
                    "Nikolayevsk",
                    "Orléans",
                    "Baardheere",
                    "Dahe",
                    "Taquarituba",
                    "Bayt Ūmmar",
                    "Chakwāl",
                    "Golbey",
                    "Wuyang",
                    "Ndibène Dahra",
                    "Odeleite",
                    "Yokotemachi",
                    "Klavdiyevo-Tarasove",
                    "Kasreman",
                    "Saint-Denis",
                    "Jaraguá",
                    "Hadabei",
                    "Guanzhou",
                    "Jesús María",
                    "Santo Tomás",
                    "Solikamsk",
                    "Medenine",
                    "Mojkovac",
                    "Skara",
                    "Sujiatuo",
                    "Maomiaoji",
                    "Sedlarevo",
                    "Doghs",
                    "San Ramon",
                    "Acobamba",
                    "Grebnevo",
                    "San Vicente de Moravia",
                    "Strasbourg",
                    "Jiazhuang",
                    "Tambalisa",
                    "Pathum Ratchawongsa",
                    "Sanshan",
                    "Likwatang Timur",
                    "Jönköping",
                    "Mangai",
                    "Goranboy",
                    "Sukonolo Krajan",
                    "Maringá",
                    "Aoufous",
                    "Tbilisskaya",
                    "Barraute",
                    "Faeanak Dua",
                    "Orekhovo-Borisovo Severnoye",
                    "El Cuy",
                    "Valence",
                    "Udi",
                    "Baisha",
                    "Zhuge",
                    "Līgatne",
                    "Rathdrum",
                    "Donnycarney",
                    "Châteaudun",
                    "Wulongshan",
                    "Santa Eulalia",
                    "Mulifanua",
                    "Przesmyki",
                    "Arlington",
                    "Dok Kham Tai",
                    "Elena",
                    "Sapele",
                    "Porto União",
                    "Fayaoué",
                    "Puricay",
                    "Juntang",
                    "Zala",
                    "Nezlobnaya",
                    "Dobrzeń Wielki",
                    "Unawatuna",
                    "Hekou",
                    "Likino-Dulevo",
                    "Tagbilaran City",
                    "Labège",
                    "Pryazovs’ke",
                    "Giade",
                    "An Lão",
                    "Szprotawa",
                    "Jincheng",
                    "Hrádek",
                    "Bárrio",
                    "Al Mughayyir",
                    "Yatunpu",
                    "Pandaan",
                    "Thatèng",
                    "Luofang",
                    "Tiraspol",
                    "Reshui",
                    "Quinta",
                    "Irasan",
                    "Huishi",
                    "Frydek",
                    "Datong",
                    "Iracemápolis",
                    "Kishiwada",
                    "Sadananya",
                    "Azovo",
                    "Vostochnoe Degunino",
                    "Hyltebruk",
                    "Ar Rubū‘",
                    "Haibara",
                    "Kanye",
                    "Matalam",
                    "Lubichowo",
                    "Dukhovnitskoye",
                    "Banjarkemuning",
                    "Mugala",
                    "Tsarychanka",
                    "Cihaurbeuti",
                    "Pasirangin Tiga",
                    "Sarnia",
                    "Dudchany",
                    "Guadalupe",
                    "Senggapi",
                    "Vienne",
                    "Gromnik",
                    "Gaoqiao",
                    "Kangar",
                    "Issoire",
                    "Sukajadi",
                    "Jicomé",
                    "Sâmraông",
                    "Tomaszów Mazowiecki",
                    "Guanbuqiao",
                    "Xiushan",
                    "Girihieum",
                    "Šimanovci",
                    "Molagavita",
                    "Lakhdenpokh’ya",
                    "Wysoka Strzyżowska",
                    "Selikhino",
                    "Kasamatsuchō",
                    "Ávato",
                    "Dongchuan",
                    "Jurovski Dol",
                    "Barbosa",
                    "Krasnoye",
                    "Yawata",
                    "Lubango",
                    "Pervomayskoye",
                    "Cigebrok",
                    "Puma",
                    "Babak",
                    "Wahawaha",
                    "Pantukan",
                    "Napoli",
                    "Lianhua",
                    "Orikum",
                    "Potoci",
                    "Baitouli",
                    "Shangyanzhuang",
                    "Gegu",
                    "Dortmund",
                    "Linköping",
                    "Białośliwie",
                    "Čáslav",
                    "Dar es Salaam",
                    "Anka",
                    "Fuwah",
                    "Cubará",
                    "Ribeirão",
                    "Zopilotepe",
                    "Erie",
                    "Stockton",
                    "Buldon",
                    "Žiželice",
                    "Kurikka",
                    "Guli",
                    "Barajalan",
                    "Nagano-shi",
                    "Lughaye",
                    "Muarabuliti",
                    "Chaparral",
                    "Serra D'El Rei",
                    "Henghe",
                    "Barrie",
                    "Mutangyuan",
                    "Tilcara",
                    "Sainte-Thérèse",
                    "Austin",
                    "Yangce",
                    "Tangcun",
                    "Magetlegar",
                    "Ketawang",
                    "La Salud",
                    "Lajeosa",
                    "Maxixe",
                    "Masarayao",
                    "Busalangga",
                    "Krasnodon",
                    "Naranjito",
                    "Saint Louis",
                    "Port Washington",
                    "Diamantino",
                    "Chabu",
                    "Santa Cruz",
                    "Rio Claro",
                    "Sandakan",
                    "Uddevalla",
                    "Claresholm",
                    "Dedenëvo",
                    "Pakel",
                    "Желино",
                    "Pirapozinho",
                    "Imielin",
                    "Cruz Alta",
                    "Czarna Woda",
                    "Maracha",
                    "Emiliano Zapata",
                    "Ermelo",
                    "Johor Bahru",
                    "Göteborg",
                    "Xunzhong",
                    "Skien",
                    "Matamey",
                    "Huaping",
                    "Mayenne",
                    "Akouda",
                    "Wuhu",
                    "Lokea",
                    "Lalukoen Dua",
                    "Khāsh",
                    "Tocota",
                    "Pensacola",
                    "Mizusawa",
                    "Pyhäranta",
                    "La Lima",
                    "Lihu",
                    "Kosikha",
                    "Zhicheng",
                    "Barice",
                    "Bukor",
                    "Ashtarak",
                    "Denver",
                    "Wang Yang",
                    "Bafatá",
                    "Baytā al Fawqā",
                    "Gusau",
                    "Nykvarn",
                    "Quimper",
                    "Kampong Speu",
                    "Afonsoeiro",
                    "Bishkek",
                    "Jembayan Hitam",
                    "Wilmington",
                    "Heshui",
                    "Balagon",
                    "Sioux Falls",
                    "Pokrovskoye",
                    "Falun",
                    "Wuyo",
                    "Bandera",
                    "Fankeng",
                    "Joubb Jannîne",
                    "Spanish Wells",
                    "Balibago",
                    "Lalagsan",
                    "Walahir",
                    "Shaxi",
                    "Vedène",
                    "Yessentuki",
                    "Rajadesa",
                    "Ciénaga",
                    "Dashiren",
                    "Dadapan",
                    "Trajouce",
                    "Xuri",
                    "Kuncen",
                    "Santol",
                    "Changle",
                    "Nanjiao",
                    "Heby",
                    "Salitral",
                    "Xiadu",
                    "Langkou",
                    "Karangduren Dua",
                    "Shuitai",
                    "Cherven Bryag",
                    "Roubaix",
                    "Polen",
                    "Tajao",
                    "Shawnee Mission",
                    "Pomahan",
                    "Nuquí",
                    "Quthing",
                    "Buynichy",
                    "Shuitou",
                    "Dire Dawa",
                    "Sukorejo",
                    "Baruny",
                    "Sremska Mitrovica",
                    "Radekhiv",
                    "Yuscarán",
                    "Garibaldi",
                    "Yahotyn",
                    "Prao",
                    "Vavuniya",
                    "Tapera",
                    "Jiangzhou",
                    "Oldřišov",
                    "Lucan",
                    "Kukawa",
                    "Cherskiy",
                    "Midlands",
                    "Cairima",
                    "Liufang",
                    "Mugan",
                    "Concepción de Ataco",
                    "Sanhe",
                    "Cimanggu",
                    "Primorsko-Akhtarsk",
                    "Zhongbao",
                    "Mabini",
                    "Sanlicheng",
                    "Smolyan",
                    "Boca de Parita",
                    "Rutana",
                    "Zengji",
                    "Santa Fe",
                    "Subulussalam",
                    "Likiep",
                    "Puerto Ayacucho",
                    "Rouen",
                    "Dubai",
                    "La Huaca",
                    "Obeliai",
                    "Lopatyn",
                    "Trancas",
                    "Grajaú",
                    "Strängnäs",
                    "Serra de Santa Marinha",
                    "Cijambe",
                    "Lidun",
                    "Kurkino",
                    "Jingyang",
                    "Hannō",
                    "Yanglin",
                    "Cikuray",
                    "Drobin",
                    "Neiba",
                    "Stepnogorsk",
                    "Geneng",
                    "Marechal Cândido Rondon",
                    "Lucheng",
                    "Reshetnikovo",
                    "Santiago de Chuco",
                    "Taman",
                    "Kotadukuh",
                    "Maodao",
                    "Yongyang",
                    "Ban Phan Don",
                    "Cheongsong gun",
                    "Wuṯahpūr",
                    "London",
                    "Itoigawa",
                    "Caen",
                    "Carazinho",
                    "Xinzhou",
                    "Daliang",
                    "Phủ Thông",
                    "Vanimo",
                    "Kimitsu",
                    "Lantian",
                    "Masḩah",
                    "Shatian",
                    "Najiaying",
                    "Yamrat",
                    "Bayangol",
                    "Sơn Tây",
                    "Duobao",
                    "Wiang Nuea",
                    "Bailu",
                    "Limoncito",
                    "Den Chai",
                    "Tayabamba",
                    "Lampa",
                    "Nizhneivkino",
                    "Dobroměřice",
                    "Borlänge",
                    "Anao",
                    "Aeka",
                    "Oroqen Zizhiqi",
                    "Nugas",
                    "Gucheng",
                    "Qinghua",
                    "Şaḩneh",
                    "Artjärvi",
                    "Wushi",
                    "Haiyangsuo",
                    "Shreveport",
                    "Brgy. Nalook, kalibo",
                    "Divisoria",
                    "Ourense",
                    "At Tāj",
                    "Hŭngnam",
                    "Mi’ersi",
                    "Pylaía",
                    "Guaíra",
                    "Medina Estates",
                    "Treinta y Tres",
                    "Wat Bot",
                    "Pingyi",
                    "Kensington",
                    "Baturinggit Kaja",
                    "Sheshory",
                    "Xiaomei",
                    "Yushan",
                    "Contagem",
                    "Miringa",
                    "Zaki Biam",
                    "Terpinnya",
                    "Chengxi",
                    "Maizuru",
                    "Qiulu",
                    "Pokrovskoye-Streshnëvo",
                    "Bulawin",
                    "Łubniany",
                    "Takahagi",
                    "Aglipay",
                    "Heydərabad",
                    "Denton",
                    "Suvorov",
                    "Çobansığnaq",
                    "Pervomayskiy",
                    "Miętne",
                    "Conceição do Araguaia",
                    "Černožice",
                    "Xinji",
                    "São Raimundo Nonato",
                    "Bontoc",
                    "Becerril",
                    "Zevgolateió",
                    "Shuishaping",
                    "As Sālimīyah",
                    "Dalu",
                    "Vimmerby",
                    "Duwakbuter",
                    "Cantilan",
                    "Sepanjang",
                    "Wangba",
                    "Undurkhaan",
                    "Chok Chai",
                    "Beilun",
                    "Stanišić",
                    "Laventure",
                    "Wlingi",
                    "Casillas",
                    "Sukaraja",
                    "Villeurbanne",
                    "Wairiang",
                    "Kihniö",
                    "Bartniczka",
                    "Waekolong",
                    "Trzebinia",
                    "Krasnokamensk",
                    "Bumpe",
                    "Meilong",
                    "Timon",
                    "Zhongfeng",
                    "Ar Ramthā",
                    "Hitachi-Naka",
                    "Tambakrejo",
                    "Fergana",
                    "Capelinha",
                    "Perechyn",
                    "Zhengyangshan",
                    "Huanggexi",
                    "Mikhaylovskoye",
                    "Ljusdal",
                    "Strančice",
                    "K Bang",
                    "Fraga",
                    "Águas Formosas",
                    "Vila Ribeiro",
                    "Gumalang",
                    "Arpajon",
                    "Likupang",
                    "Kerek",
                    "Abidjan",
                    "Stuttgart",
                    "Ketangi",
                    "San Miguel Ixtahuacán",
                    "Mayong",
                    "Widuchowa",
                    "Raszowa",
                    "Jagna",
                    "Baoxia",
                    "Negotino",
                    "Massy",
                    "Belawang",
                    "Cerklje na Gorenjskem",
                    "Al ‘Āliyah",
                    "Viso",
                    "La Jagua de Ibirico",
                    "Seattle",
                    "Nigríta",
                    "Sidzina",
                    "Puchong",
                    "Guaíba",
                    "Paris 20",
                    "Guantou",
                    "Dibba Al-Hisn",
                    "Dongxi",
                    "Bunisari",
                    "Nîmes",
                    "Estância",
                    "Rudna",
                    "Shanghuang",
                    "Fiães",
                    "Sibulan",
                    "Sancha",
                    "San Pedro One",
                    "Paris 17",
                    "Lavrica",
                    "Islamey",
                    "Pujilí",
                    "Kowale Oleckie",
                    "Nyahururu",
                    "Donglinxi",
                    "Luqiao",
                    "Panglanjan",
                    "Amirdzhan",
                    "Xingang",
                    "Jingzhu",
                    "Sheffield",
                    "Al Ḩajar al Aswad",
                    "Bologoye",
                    "Ciperang",
                    "Fonte",
                    "Buckland",
                    "Le Blanc-Mesnil",
                    "Paldiski",
                    "Montpellier",
                    "Fuxi",
                    "Shikārpur",
                    "Krueng Luak",
                    "Pedreira",
                    "Stryszawa",
                    "Jingzi",
                    "Kosów Lacki",
                    "Bairan",
                    "Stod",
                    "Degeberga",
                    "Alquerubim",
                    "Vukovije Donje",
                    "Pochep",
                    "Horvati",
                    "Yuncheng",
                    "Kiuola",
                    "Librazhd-Qendër",
                    "Mūsa Khel Bāzār",
                    "Shingū",
                    "Mangkon Daja",
                    "Ya‘bad",
                    "Bangad",
                    "Töreboda",
                    "Koua",
                    "Dongqu",
                    "Santo Antônio de Jesus",
                    "Boršice",
                    "Lemland",
                    "Mawu",
                    "Cacheu",
                    "Zhaozhen",
                    "San Juan",
                    "Granadero Baigorria",
                    "Uchaly",
                    "Manas",
                    "Horní Lideč",
                    "Kuching",
                    "Avignon",
                    "Caparrapí",
                    "Capitán Bermúdez",
                    "Xiashu",
                    "Yasenskaya",
                    "Zhuoshui",
                    "Paulínia",
                    "Skinnskatteberg",
                    "Rio das Ostras",
                    "Arcos",
                    "Turinsk",
                    "Xujiafang",
                    "Cungkal",
                    "Shangqing",
                    "Sierakowice",
                    "Priupskiy",
                    "Sebewe",
                    "Thị Trấn Phú Mỹ",
                    "Makarska",
                    "Imaan",
                    "Franca",
                    "Kultuk",
                    "Mangli",
                    "Millet",
                    "Al Khāniq",
                    "Cajolá",
                    "Shiojiri",
                    "Maricá",
                    "Yangiqo‘rg‘on",
                    "Karaidel’",
                    "Namasuba",
                    "Lampuyang",
                    "Cipanas",
                    "Mulanje",
                    "São Bernardo do Campo",
                    "Uritsk",
                    "Miaotang",
                    "São Lourenço da Mata",
                    "Ożarowice",
                    "Portela",
                    "Soriano",
                    "Stari Lec",
                    "Gaio",
                    "Muli",
                    "Ongjin",
                    "Jami",
                    "Aquia",
                    "Lunenburg",
                    "Andrijaševci",
                    "Malaryta",
                    "Freiria",
                    "Kanekomachi",
                    "Odawara",
                    "København",
                    "La Aurora",
                    "Gujba",
                    "Sidon",
                    "Gijon",
                    "Roanoke",
                    "Gradil",
                    "Pingle",
                    "Jasper Park Lodge",
                    "Criação Velha",
                    "Nurmo",
                    "Bayan Ewenke Minzu",
                    "Longuita",
                    "Karlshamn",
                    "Mayo Belwa",
                    "Tama",
                    "Banyubang",
                    "Kudowa-Zdrój",
                    "Sacramento",
                    "Fond du Sac",
                    "Karlstad",
                    "Taganak",
                    "Xinkai",
                    "Muranovo",
                    "Ladysmith",
                    "Sandur",
                    "Mombasa",
                    "Tagkawayan Sabang",
                    "Týrnavos",
                    "Jutaí",
                    "Bibinje",
                    "Cibunar",
                    "Buturlinovka",
                    "Pyatnitskoye",
                    "Peishe",
                    "Pukou",
                    "Hongchuan",
                    "Salamanca",
                    "Nuevo Berlín",
                    "Kuantian",
                    "Dianbu",
                    "Pancalan",
                    "Nishinoomote",
                    "Chile Chico",
                    "Luyang",
                    "Comandante Luis Piedra Buena",
                    "Birsa",
                    "Belišće",
                    "Pocohuanca",
                    "Kafir Qala",
                    "Girsereng",
                    "Morje",
                    "Gbadolite",
                    "Ebetsu",
                    "Arras",
                    "Banjar Penyalin",
                    "Imsida",
                    "Bang Rakam",
                    "Ihuari",
                    "Mili",
                    "Kilim",
                    "Xinxikou",
                    "Dębnica Kaszubska",
                    "Freixo de Numão",
                    "Bhunya",
                    "San Ramón",
                    "Yubileyny",
                    "Xinchenglu",
                    "Lipu",
                    "Khantaghy",
                    "Berea",
                    "Mantingantengah",
                    "Corinto",
                    "Agua Fría",
                    "Grenoble",
                    "Richmond",
                    "Krajan Jamprong",
                    "Isehara",
                    "Altavista",
                    "Odemira",
                    "Nanyaojie",
                    "Ninh Hòa",
                    "Khorlovo",
                    "Geita",
                    "Harstad",
                    "Arroyo Salado",
                    "Sevilla",
                    "Minuwangoda",
                    "Glinka",
                    "Chaoyang",
                    "Banān",
                    "Shuanghe",
                    "Santa Ana",
                    "Setaka",
                    "Kyenjojo",
                    "Santa Cecilia",
                    "Peñal",
                    "São Miguel do Rio Torto",
                    "Georgetown",
                    "Mungging",
                    "Ait Ali",
                    "Komenda",
                    "Baguim do Monte",
                    "Gielniów",
                    "Arjona",
                    "Dayou",
                    "Barranca",
                    "Stockholm",
                    "Tarłów",
                    "Belalcazar",
                    "Vryburg",
                    "Kirzhach",
                    "Lop Buri",
                    "Saltpond",
                    "Barroso",
                    "Aurora",
                    "Providencia",
                    "Pacucha",
                    "Reisdorf",
                    "Bibai",
                    "Sernovodsk",
                    "Palmito",
                    "Alvalade",
                    "Hengli",
                    "Los Andes",
                    "Huilong",
                    "Komsomol’s’ke",
                    "Koronadal",
                    "Dehī",
                    "Votuporanga",
                    "Goubangzi",
                    "Kafir Yasif",
                    "Artashat",
                    "Nizhniy Tsasuchey",
                    "Srabah",
                    "San Isidro",
                    "Agen",
                    "Novotroitsk",
                    "Vostryakovo",
                    "Serednye",
                    "Bajo Naranjillo",
                    "Paraíso",
                    "Trafaria",
                    "Pepe",
                    "Néma",
                    "Luna",
                    "Xinkaikou",
                    "Waldbillig",
                    "Carig",
                    "Isnos",
                    "Jiexiu",
                    "Boden",
                    "Valladolid",
                    "Cabaret",
                    "Al Karmil",
                    "Sinisian",
                    "Bolorejo",
                    "Tarkwa",
                    "Hongsung",
                    "Nabeul",
                    "Sigaozhuang",
                    "Atouguia",
                    "Wiri",
                    "Donostia-San Sebastian",
                    "Huangshi",
                    "Arkalyk",
                    "Arranhó",
                    "Waihi Beach",
                    "Charikar",
                    "Svetlyy",
                    "Guardizela",
                    "Huanggu",
                    "Guangli",
                    "Coayllo",
                    "Surkhet",
                    "Jetis",
                    "Rokiciny",
                    "Keratéa",
                    "Bosaso",
                    "Poligny",
                    "Villa Mercedes",
                    "Birendranagar",
                    "Santa Catalina - Dique Lujan",
                    "Hollola",
                    "Shuangshipu",
                    "Tögrög",
                    "Staten Island",
                    "Lere",
                    "Le Cannet",
                    "Tomaševac",
                    "Zheleznogorsk-Ilimskiy",
                    "Messina",
                    "Tiebukenwusan",
                    "Gayam",
                    "Liushui",
                    "Tha Bo",
                    "Gongchenqiao",
                    "Dongle",
                    "Trondheim",
                    "Al ‘Aqabah",
                    "Jōetsu",
                    "Srinagarindra",
                    "Lile",
                    "Liangli",
                    "Manassas",
                    "Shahezi",
                    "Libertad",
                    "Petare",
                    "Lunec",
                    "Xintang",
                    "Kumagaya",
                    "Barrio San Luis",
                    "Renfrew",
                    "Ozorków",
                    "Huasahuasi",
                    "Jasionów",
                    "May Pen",
                    "Trambalan",
                    "Riangkroko",
                    "Michurinskoye",
                    "Baton Rouge",
                    "Nicolet",
                    "Raas",
                    "Ōno-hara",
                    "Chinchaypujio",
                    "Tanguiéta",
                    "Andoany",
                    "Phoenix",
                    "Hasaki",
                    "Quebracho",
                    "Głogówek",
                    "Hammam Sousse",
                    "Nanshi",
                    "Lianozovo",
                    "Guaçuí",
                    "Kyrylivka",
                    "Łętownia",
                    "Horad Rechytsa",
                    "Kālābāgh",
                    "Bokoro",
                    "Baishi",
                    "Mörrum",
                    "Espinillo",
                    "Tanza",
                    "Podolí",
                    "Angan",
                    "Valle de La Pascua",
                    "Ciasna",
                    "Kamyshevatskaya",
                    "Bojongsari",
                    "Hoxtolgay",
                    "Rožmitál pod Třemšínem",
                    "Dakhla",
                    "Manjing",
                    "Mazongling",
                    "Kota Bharu",
                    "Zhangxiong",
                    "Yanhe",
                    "Evansville",
                    "Zhongzuiling",
                    "Robertsfors",
                    "Kawaguchi",
                    "Tapakrejo",
                    "Guangming",
                    "Wanjiazhuang",
                    "Washington",
                    "Bluefields",
                    "Ḩuwwārah",
                    "Artémida",
                    "Bourgoin-Jallieu",
                    "Norak",
                    "Shuishiying",
                    "Tazhuang",
                    "Dongxiaokou",
                    "Tashanta",
                    "Helsingborg",
                    "Krajan Kedungsalam",
                    "Planeta Rica",
                    "Älvdalen",
                    "Curuan",
                    "Ica",
                    "Xiangqiao",
                    "Parungjawa",
                    "Macheke",
                    "Steinfort",
                    "Évreux",
                    "Rislane",
                    "Xiehu",
                    "Lubowidz",
                    "Thị Trấn Sìn Hồ",
                    "Hồ Xá",
                    "São Francisco do Conde",
                    "Wadungasri",
                    "Moñitos",
                    "Americana",
                    "Fenghuo",
                    "Gorgān",
                    "Phúc Yên",
                    "Krajan Karangsari",
                    "Koror Town",
                    "Alagoinhas",
                    "Vingåker",
                    "Ţayyibat al Imām",
                    "Kirkton",
                    "Gweedore",
                    "Huiwen",
                    "Sinegor'ye",
                    "Grabica",
                    "Amgalang",
                    "Igang",
                    "Miðvágur",
                    "Nakasongola",
                    "Gjegjan",
                    "Liliongan",
                    "Cañazas",
                    "Sindanghayu",
                    "Santa Cruz do Sul",
                    "Ballina",
                    "Duma",
                    "Trogan Barat",
                    "Damiao",
                    "Hrob",
                    "Kuala Lumpur",
                    "Campelos",
                    "Sūq Şirwāḩ",
                    "Ulaan-Ereg",
                    "La Condamine",
                    "Las Vegas, Santa Barbara",
                    "Kuantan",
                    "Besuki",
                    "Mabyan",
                    "Moses",
                    "Makur",
                    "Parapat",
                    "Shatou",
                    "Kowalewo Pomorskie",
                    "Kuusjoki",
                    "Xijia",
                    "Mūḩ Ḩasan",
                    "Palmas De Gran Canaria, Las",
                    "Castelo de Vide",
                    "Aveleda",
                    "General Arenales",
                    "Papringan"
            };
        }
        return mLoadedData;
    }
}
