package com.infoedge.jrandomizer.providers;

/**
 * Created by gagandeep on 31/7/16.
 */

public class LinkedInSkillProvider extends Provider<String[]> {
    private LinkedInSkillProvider(Class<String[]> clazz) {
        super(clazz);
    }

    @Override
    public String[] provide() {
        if (mLoadedData == null) {
            mLoadedData = new String[]{
                    "Trend Analysis",
                    "Seismic Attributes",
                    "NPDES",
                    "HP XP",
                    "Norton Ghost",
                    "RSVP-TE",
                    "XHTML",
                    "JSON",
                    "Jive",
                    "HCM Processes &amp; Forms",
                    "Custom CMS Development",
                    "EF",
                    "Corporate Law",
                    "Data Mining",
                    "Agile Project Management",
                    "MMORPG",
                    "Animal Work",
                    "Axis2",
                    "Scripting",
                    "OAuth",
                    "Hodes IQ",
                    "Rollout",
                    "Microbiology",
                    "Horticulture",
                    "Relationship Building",
                    "EGL",
                    "User-centered Design",
                    "EPiServer",
                    "Business Rules",
                    "XML Sitemaps",
                    "IOS Firewall",
                    "OASIS",
                    "Slide Shows",
                    "CFX",
                    "Evangelism",
                    "DVD Duplication",
                    "GXT",
                    "T-SQL Stored Procedures",
                    "Hardware Architecture",
                    "VMware View",
                    "Chi Kung",
                    "Bash",
                    "Luxury Goods",
                    "BCA Protein Assay",
                    "Food",
                    "PMB",
                    "IAS 39",
                    "Sports Coaching",
                    "VRS",
                    "Transitional Justice",
                    "Basel III",
                    "Dry Eye",
                    "Business Journalism",
                    "RIP",
                    "NAS",
                    "Personal Training",
                    "XMLHTTP",
                    "QAS",
                    "1H NMR",
                    "TM1",
                    "vShield",
                    "DMVPN",
                    "BTO",
                    "PVTsim",
                    "Business Intelligence Tools",
                    "Yeast",
                    "Efficent",
                    "Electrical Engineering",
                    "Hospitality Industry",
                    "Blue Ocean Strategy",
                    "Ulead VideoStudio",
                    "SAP EBP",
                    "Canon XH-A1",
                    "Powder X-ray Diffraction",
                    "Epoxy",
                    "OTRS",
                    "Akamai",
                    "ERP Software",
                    "Summation iBlaze",
                    "GWT",
                    "MRDs",
                    "GLP",
                    "Vray",
                    "Hmong",
                    "WMI",
                    "Nastran",
                    "Variable Data Printing",
                    "Oncology",
                    "Yamaha Digital Consoles",
                    "FNMA",
                    "Blackberry",
                    "Home Staging",
                    "NCLB",
                    "Ethical Decision Making",
                    "CMC",
                    "Honeywell DCS",
                    "Style Guides",
                    "Zyxel",
                    "Oligonucleotide Synthesis",
                    "MBCI",
                    "Multithreading",
                    "MPI",
                    "Music History",
                    "Situational Awareness",
                    "eEye Retina",
                    "Legal Liability",
                    "Vendor Relations",
                    "Software Project Management",
                    "LNG",
                    "IBM Rational Tools",
                    "DDR",
                    "Professional Ethics",
                    "PBX",
                    "Tour Operators",
                    "Title Insurance",
                    "PMI",
                    "Roofers",
                    "Fractional Ownership",
                    "Veneers",
                    "Ticketing",
                    "US Tax",
                    "SSD",
                    "Exercise Physiology",
                    "Nokia Qt",
                    "Alumni Relations",
                    "SLES",
                    "SDA",
                    "Wind Turbines",
                    "ODS",
                    "Banking",
                    "Zoning",
                    "Drawing",
                    "RRC",
                    "IP VPN",
                    "Public Relations",
                    "On Location",
                    "AOD",
                    "QMF",
                    "CFIA",
                    "Oracle Identity Manager",
                    "IAM",
                    "HSE Management Systems",
                    "SBT",
                    "Zumba",
                    "TJC",
                    "Yellow Pages",
                    "NGOs",
                    "Arbitration",
                    "CMC Regulatory Affairs",
                    "CVE",
                    "DHCPv6",
                    "Cyberlaw",
                    "Justice",
                    "LabWindows/CVI",
                    "Software Design",
                    "Microsoft Exchange",
                    "Omnis",
                    "GMLAN",
                    "Healthcare Management",
                    "Academic Writing",
                    "Erosion",
                    "Epi Info",
                    "FBO",
                    "AC Nielsen",
                    "Aerial Lifts",
                    "GNU Make",
                    "MMIS",
                    "Renewable Energy",
                    "XMPP",
                    "Oil &amp; Gas",
                    "IBM Mainframe",
                    "CTMS",
                    "Humanitarian Assistance",
                    "Jets",
                    "HSM",
                    "Early Childhood Development",
                    "International Tax",
                    "GWAS",
                    "IBM pSeries",
                    "Energy Efficiency",
                    "NDIS",
                    "IT Law",
                    "Eclipse RCP",
                    "Jazz",
                    "Hazard Recognition",
                    "DFLSS",
                    "Hyperion Reports",
                    "MDS",
                    "DMU",
                    "XStream",
                    "GSM",
                    "Technical Recruiting",
                    "Norwegian",
                    "News Writing",
                    "Analytics",
                    "KBOX",
                    "Tax Returns",
                    "xPC Target",
                    "Avid",
                    "Editorial Illustrations",
                    "Law Enforcement",
                    "Media Relations",
                    "JIS",
                    "Overseas Production",
                    "Yacht Deliveries",
                    "Key Account Management",
                    "Data Warehousing",
                    "Cross-functional Coordination",
                    "Tactics",
                    "Storytelling",
                    "Healthcare Information Technology",
                    "WF",
                    "WS",
                    "PyUnit",
                    "Digital Printing",
                    "Secretarial Skills",
                    "UDP",
                    "LLBLGen",
                    "Ruby on Rails",
                    "Team Building",
                    "EEO Reporting",
                    "Job Coaching",
                    "Kaledo",
                    "Automotive Aftermarket",
                    "Zoom",
                    "High Availability",
                    "CGL",
                    "SharePoint Server",
                    "IRI",
                    "ISTQB",
                    "SDI",
                    "XSL-FO",
                    "Mathematical Modeling",
                    "LSS",
                    "Commercial Real Estate",
                    "Salesforce.com",
                    "Payroll Taxes",
                    "SGSN",
                    "PDA",
                    "Ubiquitous Computing",
                    "Microsoft Dynamics SL",
                    "Knee",
                    "Luciferase Assay",
                    "Numerical Simulation",
                    "DMPK",
                    "Quantitative Analytics",
                    "Vulnerability Research",
                    "Mobile Applications",
                    "Manual Therapy",
                    "Clerical Skills",
                    "Natural Resource Management",
                    "User Experience",
                    "SQR",
                    "Firewalls",
                    "Shared Services",
                    "Verilog",
                    "Oxygen XML Editor",
                    "RPG Free",
                    "Early Childhood Education",
                    "MSA",
                    "MCSA Security",
                    "RSpec",
                    "FMCG",
                    "FF&amp;E",
                    "Kinect",
                    "Zumba Instruction",
                    "TCP/IP",
                    "Kundalini Yoga",
                    "OSHA 30-Hour",
                    "FTIR",
                    "Swimming",
                    "Editorial",
                    "Trade Marketing",
                    "Security Audits",
                    "Rural Community Development",
                    "Real Estate Transactions",
                    "Succession Planning",
                    "MMIC",
                    "Web Content Management",
                    "Credit Analysis",
                    "SWAT",
                    "Software Quality Assurance",
                    "Koine Greek",
                    "Aquaculture",
                    "XNA",
                    "JavaScript",
                    "Working at Height",
                    "Ghost Imaging",
                    "Fashion GPS",
                    "DBAccess",
                    "JPA",
                    "Fine Art",
                    "LPR",
                    "Dynamic Speaker",
                    "Validation",
                    "Year End Accounts",
                    "Junior Golf",
                    "Music Education",
                    "NSI",
                    "Scheduling",
                    "QoS",
                    "VLR",
                    "DVB-H",
                    "Ownership",
                    "ENOVIA LCA",
                    "TPX",
                    "Typography",
                    "Nslookup",
                    "BDD",
                    "Fraud Detection",
                    "OMNI",
                    "Nursing",
                    "UEFI",
                    "Kantar",
                    "Allergic Rhinitis",
                    "DDI",
                    "VRF",
                    "JCAHO",
                    "Kinetics",
                    "TCLEOSE Instruction",
                    "Site Plans",
                    "FTPS",
                    "Open XML",
                    "Wufoo",
                    "Listings",
                    "Gift Tax",
                    "JBuilder",
                    "BFSI",
                    "Facilities Management",
                    "Fund Of Funds",
                    "Pre-owned",
                    "QSI",
                    "International Sales",
                    "Pallet Jack",
                    "FP",
                    "Federal Government",
                    "Mythology",
                    "Naval Architecture",
                    "QPS",
                    "Powers of Attorney",
                    "Industrial Ethernet",
                    "Yoga Instruction",
                    "NRC",
                    "Agrochemicals",
                    "HGV",
                    "KML",
                    "CDM Coordinator",
                    "PE",
                    "Litigation",
                    "CQG",
                    "HBSS",
                    "Eiffel",
                    "Sales",
                    "Eyewonder",
                    "Warehouse Management",
                    "Pymol",
                    "Stage Make-up",
                    "TI DSPs",
                    "Biodiversity",
                    "Short Sales",
                    "UHV",
                    "ETL Tools",
                    "Business Efficiency",
                    "HR Software",
                    "Xeriscaping",
                    "Administration",
                    "TSP",
                    "Type Approval",
                    "VHDL",
                    "Public Policy",
                    "DVB-C",
                    "LPN",
                    "CTR",
                    "RF Circuits",
                    "TMW",
                    "Development Economics",
                    "XML Gateway",
                    "Unfair Competition",
                    "Jerseys",
                    "HFM",
                    "CQ",
                    "Oversight",
                    "Baan ERP",
                    "Kung Fu",
                    "Microsoft Dynamics NAV",
                    "CPOE",
                    "Sales Process",
                    "Umbrellas",
                    "Office Equipment",
                    "Advertising",
                    "PDMLink",
                    "Occlusion",
                    "Yield",
                    "CFM",
                    "Theory",
                    "Music Theory",
                    "OB/GYN",
                    "OmniGraffle",
                    "MFG-Pro",
                    "Linux",
                    "IxChariot",
                    "Sports Nutrition",
                    "Wound Care",
                    "VPLS",
                    "IRIS",
                    "Inventory Control",
                    "Oracle OLAP",
                    "System Testing",
                    "MCH",
                    "TFM",
                    "Underground Mining",
                    "ETL",
                    "Operational Planning",
                    "Songwriting",
                    "Quality Auditing",
                    "Java Applets",
                    "Speech Writing",
                    "KRAs",
                    "Sales Presentations",
                    "DFMA",
                    "Xetra",
                    "LLC",
                    "GBS",
                    "MLSS",
                    "QNXT",
                    "Easements",
                    "SDL",
                    "FMS",
                    "Yarn",
                    "Managerial Finance",
                    "Environmental Science",
                    "SAP BI",
                    "CWNA",
                    "Knee Pain",
                    "White Papers",
                    "Zinc",
                    "Global Sourcing",
                    "Six Sigma",
                    "Knowledge Management",
                    "Union Avoidance",
                    "NSPS",
                    "ICH-GCP",
                    "Cycle Time Reduction",
                    "MDF",
                    "GDAL",
                    "Dual Diagnosis",
                    "Investment Banking",
                    "ITIL v3 Foundations Certified",
                    "Koi Ponds",
                    "Automotive Engineering",
                    "Xalan",
                    "JProbe",
                    "Rhinoplasty",
                    "Mac OS",
                    "Krakatoa",
                    "DNA Extraction",
                    "Military Aviation",
                    "Fume FX",
                    "MSP430",
                    "DVD",
                    "Medical Affairs",
                    "Brand Equity",
                    "Market Analysis",
                    "SNA",
                    "AOP",
                    "Gospel",
                    "NBS Specification",
                    "Pro Tools",
                    "Ecological Restoration",
                    "GPIB",
                    "CVS",
                    "FF&amp;E Specifications",
                    "IAR Embedded Workbench",
                    "Uniform Combined State Law",
                    "Analytical Skills",
                    "Healing",
                    "FP-C",
                    "Game Design",
                    "MCAD",
                    "RSoft",
                    "3Com NBX",
                    "Oracle E-Business Suite",
                    "Allen-Bradley",
                    "Military Affairs",
                    "Production Planning",
                    "OWL",
                    "Hand Knitting",
                    "TTL",
                    "Consulting",
                    "OBIEE",
                    "EBA",
                    "Land Use",
                    "TMN",
                    "Women Owned Business",
                    "TCA",
                    "NCBI",
                    "Mobile Marketing",
                    "DVB-T",
                    "Routing",
                    "SDSF",
                    "Snooker",
                    "DC-DC",
                    "TMAP",
                    "Eggs",
                    "Lubricants",
                    "RMA",
                    "JAX-WS",
                    "Statistics",
                    "Ion Exchange",
                    "QRadar",
                    "DNS Management",
                    "Affiliate Management",
                    "Small Business Online Marketing",
                    "VMware Player",
                    "Patient Safety",
                    "BOSIET",
                    "Yellow Book",
                    "Social Psychology",
                    "LC-MS",
                    "Employee Engagement",
                    "Sap Fm",
                    "Data Center",
                    "HtmlUnit",
                    "PSpice",
                    "IXIA",
                    "PDH",
                    "European Integration",
                    "Airline Management",
                    "Mycology",
                    "DTI",
                    "Trade Shows",
                    "DCF Valuation",
                    "Curating",
                    "Web Analytics",
                    "DHCP",
                    "DGPS",
                    "OE",
                    "Lifestyle",
                    "SAP PM Module",
                    "TLC",
                    "Documentation",
                    "HQL",
                    "Single Family Homes",
                    "Banquets",
                    "TMDLs",
                    "Academic Advising",
                    "SAP SRM",
                    "Vessel Operations",
                    "VSD",
                    "LCMS",
                    "Biotechnology",
                    "Alternative Dispute Resolution",
                    "NPV",
                    "ASIC",
                    "VxFS",
                    "Enterprise Architecture",
                    "WCDMA",
                    "FCAW",
                    "FxCop",
                    "CQI",
                    "Wills",
                    "Following Up",
                    "FQL",
                    "Petroleum Geology",
                    "Key Performance Indicators",
                    "Nuclear",
                    "WCCP",
                    "RF Troubleshooting",
                    "Cerner CCL",
                    "Oracle BPEL",
                    "Experimentation",
                    "Qbasic",
                    "Time &amp; Attendance",
                    "JCreator",
                    "Mplus",
                    "FX Trading",
                    "eGRC",
                    "RTOS",
                    "Bathrooms",
                    "ESL",
                    "Recruiting",
                    "Kodaly",
                    "MPLS",
                    "eEmpact",
                    "Olfaction",
                    "Capital Equipment Sales",
                    "Front Office",
                    "Immunology",
                    "TSRM",
                    "QKA",
                    "xCP",
                    "TTD",
                    "PCS7",
                    "Skin Care Products",
                    "BTE",
                    "GTK",
                    "HMIs",
                    "Enterprise Risk Management",
                    "EHR",
                    "CTQ",
                    "Recruitment Advertising",
                    "HR Transformation",
                    "New Home Sales",
                    "Kinetic Typography",
                    "Custom Homes",
                    "Kronos Timekeeping",
                    "Csh",
                    "Influence Others",
                    "AHA",
                    "VNA",
                    "Juniper JNCIA",
                    "Human Resource Development",
                    "DNA fingerprinting",
                    "MVC Architecture",
                    "Young People",
                    "Digital Photography",
                    "Change Control",
                    "HSQE",
                    "Ducting",
                    "ZK",
                    "Voice Over",
                    "WCF Services",
                    "CFRA",
                    "Wellness Coaching",
                    "Unix",
                    "Business Planning",
                    "Data Quality",
                    "Time Series Analysis",
                    "MPBN",
                    "Cytogenetics",
                    "UV/Vis",
                    "InDesign",
                    "Animal Behavior",
                    "Cloud Computing",
                    "LDP",
                    "Capital Equipment",
                    "IFE",
                    "ODI",
                    "Java RMI",
                    "Latin American Studies",
                    "Culture Change",
                    "QROPS",
                    "AQL",
                    "DNS Server",
                    "RRIF",
                    "GPS Devices",
                    "Top Secret",
                    "Vector NTI",
                    "HTML5",
                    "Osteopathy",
                    "RPO",
                    "Ntop",
                    "MRI Plus",
                    "MCS",
                    "AHWD",
                    "HR Consulting",
                    "Railway",
                    "Aircraft Systems",
                    "Outdoor Recreation",
                    "Ufile",
                    "CSM",
                    "Drywall",
                    "Utility Billing",
                    "Overseas Experience",
                    "Strategic Communications",
                    "Qooxdoo",
                    "NCIE",
                    "Business Objects",
                    "Eze Castle",
                    "Object Oriented Perl",
                    "MM modules",
                    "UVM",
                    "Performance Improvement",
                    "JDA",
                    "Microsoft DNS",
                    "Geomatics",
                    "Design of Experiments",
                    "NYS Notary Public",
                    "Turkish",
                    "Linux System Administration",
                    "AMSI",
                    "EPA",
                    "WPC",
                    "Ruby",
                    "VTP",
                    "Prenuptial Agreements",
                    "Xerox Printers",
                    "Financial Risk",
                    "LSL",
                    "CPIM",
                    "Tax Preparation",
                    "Buyer Representation",
                    "KMS",
                    "Shrinkage",
                    "Outsourcing Management",
                    "Liability",
                    "LPS",
                    "Cash Flow Forecasting",
                    "MCEV",
                    "Geometric Dimensioning &amp; Tolerancing",
                    "CCIE",
                    "BTS Installation",
                    "Information Assurance",
                    "SIP",
                    "CPFR",
                    "DTDs",
                    "Phase II Environmental Site Assessments",
                    "QFD",
                    "Scrum",
                    "CADS RC",
                    "PCP",
                    "Pay TV",
                    "BBEdit",
                    "D3.js",
                    "Hair Care",
                    "HRIS Database Management",
                    "Ethernet over SDH",
                    "Embedded SQL",
                    "SMTP",
                    "GPU",
                    "Thermal Oxidizers",
                    "English",
                    "DST",
                    "HP QTP",
                    "Estate Planning",
                    "DMT",
                    "Job Analysis",
                    "Cardiac MRI",
                    "LDRA",
                    "Phase II Subsurface Investigations",
                    "Typesetting",
                    "HCS 2000",
                    "DLC",
                    "Jitterbit",
                    "Jigs",
                    "DNSSEC",
                    "CTI",
                    "Google Earth",
                    "VBScript",
                    "BCM",
                    "Geology",
                    "Tcsh",
                    "Screening",
                    "Rig",
                    "Simple IRA",
                    "QS1",
                    "Logic Pro",
                    "PMP",
                    "NDE",
                    "PostgreSQL",
                    "Raw Materials",
                    "UDF",
                    "Sales Effectiveness",
                    "DFT",
                    "QNX",
                    "XCAP",
                    "Pylons",
                    "Mobile Technology",
                    "Slope Stability",
                    "Olympic Lifting",
                    "Nutritional Counseling",
                    "Economics",
                    "DTD",
                    "Software Engineering",
                    "FX Options",
                    "NDM",
                    "IACUC",
                    "MSC Adams",
                    "Food Industry",
                    "White Box Testing",
                    "BTL Activations",
                    "SEP IRA",
                    "High Sense Of Urgency",
                    "TSM",
                    "PNR",
                    "IFRS",
                    "GPFS",
                    "Epigenetics",
                    "DFSORT",
                    "eBay",
                    "Kofax",
                    "HSEEP",
                    "JSTL",
                    "E-commerce",
                    "JVC",
                    "SDLX",
                    "Cycling",
                    "RDI",
                    "PPPoE",
                    "Rheumatology",
                    "QR",
                    "Overhaul",
                    "PMC",
                    "American English",
                    "Temporary Placement",
                    "SaaS",
                    "Poka Yoke",
                    "GNU C",
                    "Nmap",
                    "SDS-PAGE",
                    "National Security",
                    "Public Speaking",
                    "EWSD",
                    "Nursing Management",
                    "Interactive Whiteboard",
                    "Agilent ADS",
                    "VLS",
                    "Procurement Outsourcing",
                    "Static Timing Analysis",
                    "Classroom",
                    "BWA",
                    "CDPE",
                    "Quantum GIS",
                    "IOS-XR",
                    "Book Illustration",
                    "Youth Outreach",
                    "Wireless Networking",
                    "DNA ligation",
                    "Sweaters",
                    "OEM negotiations",
                    "NGN",
                    "MRTG",
                    "Cognitive Psychology",
                    "VMware",
                    "CME",
                    "Rhetoric",
                    "Automobile",
                    "Rational XDE",
                    "YUM",
                    "Occupational Therapists",
                    "Jive SBS",
                    "IVD",
                    "Runway",
                    "Switching",
                    "QPSK",
                    "International HR",
                    "Prototype.js",
                    "IT Service Management",
                    "TGI",
                    "Agile Application Development",
                    "Class Actions",
                    "SSL Certificates",
                    "GS1",
                    "Credit Unions",
                    "HP Procurve",
                    "Medical-Surgical",
                    "HP Servers",
                    "Sage 300 ERP",
                    "Mysis",
                    "LynxOS",
                    "WLAN",
                    "NRP",
                    "CVA",
                    "DBT",
                    "Owners Representative",
                    "Type 2 Diabetes",
                    "Media TV",
                    "Topographic Surveys",
                    "MBAL",
                    "CSI",
                    "SRDF",
                    "Cash Management",
                    "European Markets",
                    "Document Review",
                    "Fashion Buying",
                    "Lighting",
                    "Systems Design",
                    "Amadeus",
                    "End User Training",
                    "Kondor+",
                    "Github",
                    "CICS",
                    "RMIS",
                    "TPM",
                    "PMAs",
                    "Testing Types",
                    "VSTS",
                    "Intercollegiate Athletics",
                    "Aeroelasticity",
                    "Petrochemical",
                    "JCIDS",
                    "SWIFT Payments",
                    "Zoo",
                    "DVD Architect",
                    "Klarity",
                    "RNAseq",
                    "Veterinary",
                    "Nickel",
                    "WMS Implementations",
                    "PDM",
                    "IntelliJ IDEA",
                    "SAP XI",
                    "Sports",
                    "Property Management Systems",
                    "HSDPA",
                    "First Time Home Sellers",
                    "Tiles",
                    "DNA quantification",
                    "Oxy-acetylene",
                    "Kundalini",
                    "WFS",
                    "XATA",
                    "TPC",
                    "AWS CWI",
                    "VW",
                    "Solution Selling",
                    "Community Outreach",
                    "DSDM",
                    "ISM",
                    "BBx",
                    "Hyperion EPM",
                    "FPSO"
            };
        }
        return mLoadedData;
    }
}
